### ISSUE TITLE
Choppy client side sun animation

### ISSUE THREAD

**Issue by yooksi** [yoco-labs/odyssey#20]
Slower day/night cycle makes the sun/moon movement choppy on client.

**Comment by yooksi** [comment]
@Titus-Armillius Can you please check if this issue is present on your side, I remember this being a problem in development environment but am not sure if it affects production, and my setup might be affected by lag and other problems that might be causing this.

**Comment by Titus-Armillius** [comment]
Will do.

**Comment by Titus-Armillius** [comment]
I seem to be encountering the same issue. 

Here is a link to a video just to confirm: https://youtu.be/Mgvi3qub4tI

(config setting is -14)

**Comment by yooksi** [comment]
Okay, I am not sure if that is due to the low resolution nature of Minecraft or the client not getting synced with the server properly. I will try to investigate the issue further.
