### ISSUE TITLE
Choose a project license

### ISSUE THREAD

**Issue by yooksi** [yoco-labs/odyssey#21]
We should think carefully about how we want to license the project.
A good place to see established licenses is https://choosealicense.com/

I would recommend using [General Public License v3.0](https://choosealicense.com/licenses/gpl-3.0/). 

> Permissions of this strong copyleft license are conditioned on making available complete source code of licensed works and modifications, which include larger works using a licensed work, under the same license. Copyright and license notices must be preserved. Contributors provide an express grant of patent rights. 

It is quite permissive with what others are allowed to do with our mod.(commercial use, distribution, modification etc) provided they keep the mod open source when distributing it, do not change the license and state all the changes they've made to our work.

**Comment by Titus-Armillius** [comment]
I've had a look over the licences shown; and agree that we should go wit the GNU General Public License v3.0.
