### ISSUE TITLE
Lower temperature in shade

### ISSUE THREAD

**Issue by yooksi** [yoco-labs/odyssey#24]
It would greatly improve the temperature system by having a *shadow/ray detection system* to help implement a mechanic where shade/caves are able to provide relief by reducing the temperature.

**Comment by Titus-Armillius** [comment]
![](https://i.imgur.com/ot7YYaO.png)

Note that the green box represent the player.

**Comment by Titus-Armillius** [comment]
Time values based on this graphic:

<img src="https://gamepedia.cursecdn.com/minecraft_gamepedia/b/bc/Day_Night_Clock_24h.png?version=e98a113709261193b4159967f46c1006" width="400" height="400" />

**Comment by yooksi** [comment]
That would work great in a 2D environment but I don't see how it would work in Minecraft. Our best bet would be to figure out the position of the sun relative to the player and then `RayTrace` in the direction of the sun from players position and see if we hit a block.

**Comment by Titus-Armillius** [comment]
Wow, you can do that? Well if that works lets go with that then.

If for some reason we can't, we could have the detection system be a dome, not an arc; and take into account the horizontal angle, not just the vertical as above.

**Comment by Titus-Armillius** [comment]
![](https://i.imgur.com/gKlN3fU.png)
