### ISSUE TITLE
World temperature system

### ISSUE THREAD

**Issue by yooksi** [yoco-labs/odyssey#5]
| Period of the day | Minecraft Time |  Temperature |  Temp. increase till next period |
|--------------------|------------------|----------------|-----------------------------------|
| Midnight              | 00:00                |  -2°C               |    ↑2.5°C every hour                  |
| Dawn                   |  06:00                |  13°C              |   ↑5°C every half hour               |
| Noon                   | 12:00                  |  60°C             |    ↓5°C every hour                     |
| Dusk                    |  18:00                 |  35°C             |    ↓4°C every half hour              |                   

 - A temperature `> 45°C` will slightly blur the players vision and cause nausea; given there are no 
   blocks above the player providing protection from the sun.

  - A temperature `> 55°C` will reduce the player's current health by `20` every half hour (Minecraft Time - MT).

  - A temperature `< 4°C` will gradually reduce the player's movement speed; and will reduce their health by `10` every half hour (MT) .

- Any source of fire (e.g. campfire, torch) will increase the temperature within the a certain radius by 15°C  .

See #4 to understand the day/night cycle implementation

This temperature system should (for now) only operate when the player enters a Desert biome specifically.

**Comment by yooksi** [comment]
Am I right to assume that these temperature values are calibrated for the desert biome?

**Comment by Titus-Armillius** [comment]
Pretty much, yes.

**Comment by yooksi** [comment]
Does this mean that temperature feature will only work in deserts?

After reading [this post](https://www.reddit.com/r/Minecraft/comments/3eh7yu/the_rl_temperature_of_minecraft_biomes_revealed/) on Reddit it would seem that Minecraft already does have a temperature system where each biome is assigned a constant temperature value used to color foliage.

**Comment by yooksi** [comment]
> btw I would like to catch up on the main feature developments on the 10th if possible over voice chat if that's ok with you.

Not much to catch up at the moment, I am currently working on this feature and am in general informing you of my progress regularly. As you've seen a day or so ago in a live-stream I did me and Rellit found out how the GUI is being drawn on the screen and were able to draw a purple xp bar in place of the vanilla one. 

Now that the GUI system has been researched I will focus on implementing the temperature system in the next two days in which I will hopefully have an early system ready.

**Comment by Titus-Armillius** [comment]
Ah, sorry I misinterpreted. 

The temp values are based upon the temperature range that occurs in real life deserts.

Our temperature system should be kept separate.

**Comment by Titus-Armillius** [comment]
I would like to discuss a shadow/ray detection system to help implement a system where shade/caves are able to provide relief by reducing the temperature.

**Comment by yooksi** [comment]
That's a great idea! Let's move this discussion in #24
